sudo: required
services:
  - docker

before_install:
  - docker build -t shavitnetzer/docker-react .

script:
  - docker-compose up --build -d
  - bash test-script.sh $PASS
  - docker-compose down

#after_success:
#   script:
#    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
#    - docker push shavitnetzer/docker-react:001
after_success:
  - docker build -t shavitnetzer/docker-react .
#  - bash docker-push.sh $DOCKER_USERNAME $DOCKER_PASSWORD $TRAVIS_BUILD_NUMBER
#  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
#  - docker push ${DOCKER_USERNAME}/docker-react:${TRAVIS_BUILD_NUMBER}
deploy:
  provider: script
  script: 
   - bash docker-push.sh
#   - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
#   - docker push $DOCKER_USERNAME/docker-react:$TRAVIS_BUILD_NUMBER
#   - docker push shavitnetzer/docker-react:001
  on:
    branch: master
