sudo: required
services:
 - docker

before_install:
 - docker build -t shavitnetzer/docker-react .

script:
 - docker-compose up --build -d
 - curl -q localhost:8083
 - curl -q localhost:8083
 - if [ `curl -q localhost:8083` = "Number of visits is 2" ];then exit 0 ; else exit 1;fi
 - docker-compose down
