sudo: required
services:
 - docker

before_install:
 - docker build -t shavitnetzer/docker-react .

script:
 - docker-compose up --build -d
 - docker ps
 - netstat -nptul
 - curl -q -vv http://localhost:8081/
 - docker-compose down
