sudo: required
services:
  - docker

#before_install:
#  - docker build -t $DOCKER_USERNAME/docker-react:$TRAVIS_BUILD_NUMBER .

script:
  - docker-compose up --build -d
  - bash test-script.sh $PASS
  - docker-compose down

deploy:
  provider: script
  script: 
   - docker build -t $DOCKER_USERNAME/docker-react:$TRAVIS_BUILD_NUMBER .
   - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
   - docker push $DOCKER_USERNAME/docker-react:$TRAVIS_BUILD_NUMBER
  on:
    branch: master
