sudo: required
services:
 - docker

before_install:
 - docker build -t shavitnetzer/docker-react .

script:
 - docker-compose up --build -d
 - docker-compose  ps
 - netstat -nptul
 - cat index.js
 - curl -q -vv localhost:8081
 - docker-compose down
