sudo: required
services:
 - docker

before_install:
 - docker build -t shavitnetzer/docker-react .

script:
 - docker run -name docker-react shavitnetzer/docker-react -d 
 - docker ps
 - netstat -nptul
 - curl -q localhost:8081
 - docker rm -f docker-react
