sudo: required
services:
 - docker

before_install:
 - docker build -t shavitnetzer/docker-react .

script:
 - docker-compose up --build -d
 - echo $SHAV
 - bash test-script.sh
 - docker-compose down
